name:                hledger-flow
version:             0.14.0.0
synopsis:            An hledger workflow focusing on automated statement import and classification.
category:            Finance, Console
license:             GPL-3
author:              "Andreas Pauley <hledger-flow@pauley.org.za>"
maintainer:          "Andreas Pauley <hledger-flow@pauley.org.za>"
copyright:           "2018 Andreas Pauley"
github:              "apauley/hledger-flow"
bug-reports:         https://github.com/apauley/hledger-flow/issues

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Finance, Console

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README file.
description:         Please see the README on GitHub at <https://github.com/apauley/hledger-flow#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - turtle
  - path
  - path-io
  - exceptions
  - text
  - foldl
  - containers
  - time
  - stm

executables:
  hledger-flow:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fPIC
    ld-options:
    - -dynamic # change to -static for a statically linked executable. Does not work on osx

    dependencies:
    - hledger-flow
    - path
    - turtle
    - text
    - optparse-applicative

tests:
  hledger-flow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-flow
    - path
    - path-io
    - turtle
    - HUnit
    - containers
    - foldl
    - text
    - stm
