#+STARTUP: showall
#+TITLE: hledger-makeitso: Step By Step
#+PROPERTY: header-args:sh :prologue exec 2>&1 :epilogue echo :

* About This Document

This document is a [[https://www.offerzen.com/blog/literate-programming-empower-your-writing-with-emacs-org-mode][literate]] [[https://orgmode.org/worg/org-contrib/babel/intro.html][program]].
You can read it like a normal article.

But you can also open [[file:README.org][this org-mode file]] in emacs,
and execute each code snippet by pressing =C-c C-c= with your cursor on the relevant code block.

* The Story of an African Chef

Meet Gawie de Groot. Gawie is a successful [[https://en.wikipedia.org/wiki/Gonimbrasia_belina#As_food][mopane worm]] chef, based in the northernmost section of the [[https://en.wikipedia.org/wiki/Kruger_National_Park][Kruger National Park]].

In the past he used to work in a big city as an IT professional, but after a few years of this he decided to choose a quiter life
in the bushveld.

He now works at a renowned bush restaurant aptly named the "=Grillerige Groen Goggatjie=".

Demand for his traditional African cuisine has sky-rocketed, with visitors from all over Zimbabwe, Mozambique and South Africa
coming to enjoy his dishes.

Business has been good the last few years, but Gawie wants to make sure that he'll also be OK when business is down.

It is time for Gawie to take charge of his finances.

* Part 1: The First CSV Statement

Gawie followed the [[https://github.com/apauley/hledger-makeitso#build-instructions][build instructions]] and ended up with his very own =hledger-makeitso= executable.

Let's just run this =hledger-makeitso= command and see what happens...

#+NAME: hm-noargs
#+BEGIN_SRC sh :results output :exports both
hledger-makeitso
#+END_SRC

#+RESULTS: hm-noargs
#+begin_example
Manage your hledger CSV imports and classification: https://github.com/apauley/hledger-makeitso#readme

Usage: hledger-makeitso (import | report)

Available options:
  -h,--help                Show this help text

Available commands:
  import                   Converts CSV transactions into categorised journal files
  report                   Generate Reports

#+end_example

Well OK, at least it prints some helpful output.

Gawie wants to import his CSV statements. Luckily the =import= subcommand has a bit of help text as well:

#+NAME: hm-import-help
#+BEGIN_SRC sh :results org :exports both
hledger-makeitso import --help
#+END_SRC

#+RESULTS: hm-import-help
#+BEGIN_SRC org
Usage: hledger-makeitso import [BASEDIR]
  Converts CSV transactions into categorised journal files

Available options:
  BASEDIR                  The hledger-makeitso base directory
  -h,--help                Show this help text

#+END_SRC


Gawie starts by creating a new directory specifically for his hledger journals:

#+NAME: rm-fin-dir
#+BEGIN_SRC shell :results none :exports results
rm -rf my-finances
#+END_SRC

#+NAME: new-fin-dir
#+BEGIN_SRC shell :results none :exports both
mkdir my-finances
#+END_SRC

Now he can point the import to his new finances directory:
#+NAME: import1
#+BEGIN_SRC sh :results org :exports both
hledger-makeitso import ./my-finances
#+END_SRC

#+RESULTS: import1
#+BEGIN_SRC org
hledger-makeitso: user error (Unable to find CSV import dir at ./my-finances/import)

#+END_SRC

Hmmm, an error.
Looking at the [[https://github.com/apauley/hledger-makeitso#readme][project README]], it seems that =hledger-makeitso= looks for its input files in some very specific directories.

There should be an =import= directory, and under that a directory named after a bank, followed by a directory for the account and so on.

Gawie's salary is deposited into his cheque account at =Bogart Bank=, so this seems like a good account to start with:

#+NAME: first-input-file
#+BEGIN_SRC shell :results none :exports both
mkdir -p my-finances/import/bogart/cheque/1-in/2016/
cp Downloads/Bogart/123456789_2016-03-30.csv my-finances/import/bogart/cheque/1-in/2016/
#+END_SRC

Let's see what our tree structure looks like now:
#+NAME: tree-after-1st-file
#+BEGIN_SRC shell :results org :exports both
tree my-finances/import
#+END_SRC

#+RESULTS: tree-after-1st-file
#+BEGIN_SRC org
my-finances/import
└── bogart
    └── cheque
        └── 1-in
            └── 2016
                └── 123456789_2016-03-30.csv

4 directories, 1 file
#+END_SRC

It is time to add what we have to source control.

#+NAME: git-init
#+BEGIN_SRC shell :results none :exports both
cd my-finances/
git init .
git add .
git commit -m 'Initial commit'
cd ..
#+END_SRC

Let's try the import again:
#+NAME: import2
#+BEGIN_SRC sh :results org :exports both
hledger-makeitso import ./my-finances
#+END_SRC

#+RESULTS: import2
#+BEGIN_SRC org
hledger: user error (the first CSV record ["2","123456789","'MNR GAWIE DE GROOT'","'BOGART TJEKREKENING'"] has 4 fields but ["3","","'Staat'"] has 3)
hledger-makeitso: ProcFailed {procCommand = "hledger", procArguments = ["print","--rules-file","./my-finances/import/bogart/cheque/bogart-cheque.rules","--file","./my-finances/import/bogart/cheque/1-in/2016/123456789_2016-03-30.csv","--output-file","./my-finances/import/bogart/cheque/3-journal/2016/123456789_2016-03-30.journal"], procExitCode = ExitFailure 1}

#+END_SRC

Another cryptic error.

This one is caused by this missing [[http://hledger.org/csv.html][rules file]]:
=./my-finances/import/bogart/cheque/bogart-cheque.rules=

After looking through the [[http://hledger.org/csv.html][hledger documentation on CSV rules files]],
Gawie concludes that the dates in Bogart Bank's CSV statement is incompatible with basic logic, reason and decency.

Luckily he isn't the only one suffering at the hands of bureaucratic incompetence: someone else has already written [[https://github.com/apauley/fnb-csv-demoronizer][a script]] to
fix stupid dates like those used by Bogart Bank.

This looks like a job for a [[https://github.com/apauley/hledger-makeitso#the-preprocess-script][preprocess script]].
Maybe we can get away with just a symbolic link...

Gawie adds the CSV transformation script as a submodule to his repository:

#+NAME: git-submodule-demoronizer
#+BEGIN_SRC sh :results none :exports both
cd my-finances/
git submodule add https://github.com/apauley/fnb-csv-demoronizer.git
git commit -m 'Added submodule: fnb-csv-demoronizer'
cd ..
#+END_SRC

=hledger-makeitso= looks for a file named [[https://github.com/apauley/hledger-makeitso#the-preprocess-script][preprocess]] in the account directory.

Gawie just creates a symbolic link named =preprocess=.
This works because the downloaded script takes an input file and an output file as the first two positional arguments,
very much as the =preprocess= script would expect.
And luckily it ignores the other parameters that =hledger-makeitso= sends through.

#+NAME: symlink-demoronizer
#+BEGIN_SRC sh :results none :exports both
cd my-finances/import/bogart/cheque
ln -s ../../../fnb-csv-demoronizer/fnb-csv-demoronizer preprocess
#+END_SRC

Now when we try the import again, it still displays an error due to our missing rules file.
But this time we can see that our statement was preprocessed:
#+NAME: import3
#+BEGIN_SRC sh :results none :exports both
hledger-makeitso import ./my-finances
#+END_SRC

#+NAME: head-preprocess
#+BEGIN_SRC sh :results org :exports both
head -n 2 my-finances/import/bogart/cheque/2-preprocessed/2016/123456789_2016-03-30.csv
#+END_SRC

#+RESULTS: head-preprocess
#+BEGIN_SRC org
"5","'Nommer'","'Datum'","'Beskrywing1'","'Beskrywing2'","'Beskrywing3'","'Bedrag'","'Saldo'","'Opgeloopte Koste'"
"5","1","2016-02-28","#Monthly Bank Fee","","","-500.00","40000.00",""

#+END_SRC

#+NAME: git-checkpoint-preprocess
#+BEGIN_SRC sh :results none :exports results
cd my-finances/
git add .
git commit -m 'The preprocessed CSV now has dates we can work with!'
cd ..
#+END_SRC

Now that we have sane dates in a CSV file, let's try to create a [[http://hledger.org/manual.html#csv-rules][rules file]]:
#+NAME: bogart-cheque-rules-file
#+BEGIN_SRC hledger :tangle my-finances/import/bogart/cheque/bogart-cheque.rules
skip 1

fields _, _, date, desc1, desc2, desc3, amount, balance, _

currency R
status *

account1 Assets:Current:Gawie:Bogart:Cheque
description %desc1/%desc2/%desc3
#+END_SRC

Gawie saves this file as =my-finances/import/bogart/cheque/bogart-cheque.rules=.

#+NAME: tangle-rules
#+BEGIN_SRC emacs-lisp :results none :exports results
; Narrator: this just tells emacs to write out the rules file. Carry on.
(org-babel-tangle-file (buffer-file-name))
#+END_SRC

#+NAME: git-checkpoint-rules
#+BEGIN_SRC sh :results none :exports results
cd my-finances/
git add .
git commit -m 'A CSV rules file'
cd ..
#+END_SRC

This time the import is successful, and we see a number of newly generated files:
#+NAME: import4
#+BEGIN_SRC sh :results org :exports both
hledger-makeitso import ./my-finances
tree my-finances
#+END_SRC

#+RESULTS: import4
#+BEGIN_SRC org
my-finances
├── fnb-csv-demoronizer
│   ├── fnb-csv-demoronizer
│   └── README.org
├── import
│   └── bogart
│       ├── bogart.journal
│       └── cheque
│           ├── 1-in
│           │   └── 2016
│           │       └── 123456789_2016-03-30.csv
│           ├── 2-preprocessed
│           │   └── 2016
│           │       └── 123456789_2016-03-30.csv
│           ├── 3-journal
│           │   └── 2016
│           │       └── 123456789_2016-03-30.journal
│           ├── bogart-cheque.journal
│           ├── bogart-cheque.rules
│           ├── opening.journal
│           └── preprocess -> ../../../fnb-csv-demoronizer/fnb-csv-demoronizer
└── import-all.journal

10 directories, 11 files

#+END_SRC

Bogart Bank's CSV file has been transformed into an =hledger= journal file.

This is the first transaction in the file:
#+NAME: head-1st-journal
#+BEGIN_SRC sh :results org :exports both
head -n 3 my-finances/import/bogart/cheque/3-journal/2016/123456789_2016-03-30.journal
#+END_SRC

#+RESULTS: head-1st-journal
#+BEGIN_SRC org
2016/02/28 * #Monthly Bank Fee//
    Assets:Current:Gawie:Bogart:Cheque        R-500.00 = R40000.00
    expenses:unknown                           R500.00

#+END_SRC

#+NAME: git-checkpoint-1st-journal
#+BEGIN_SRC sh :results none :exports results
cd my-finances/
git add .
git commit -m 'My first imported journal'
cd ..
#+END_SRC

Can hledger show us some data?

#+NAME: hledger-err-balance
#+BEGIN_SRC sh :results org :exports both
hledger -f my-finances/import-all.journal incomestatement
#+END_SRC

#+RESULTS: hledger-err-balance
#+BEGIN_SRC org
hledger: balance assertion error in "my-finances/import/bogart/cheque/3-journal/2016/123456789_2016-03-30.journal" (line 2, column 56):
in transaction:
2016/02/28 * #Monthly Bank Fee//
    Assets:Current:Gawie:Bogart:Cheque        R-500.00 = R40000.00
    expenses:unknown                           R500.00
after posting:
    Assets:Current:Gawie:Bogart:Cheque    R-500.00
balance assertion details:
date:       2016/02/28
account:    Assets:Current:Gawie:Bogart:Cheque
commodity:  R
calculated: R-500.00
asserted:   R40000.00 (difference: +R40500.00)


#+END_SRC

Not yet - we have a balance assertion error.
=hledger= thinks the balance should be =-R500=, but our import asserted that it should be =R40000=.

Remember the =balance= field we added to the rules file?
#+NAME: balance-field-rules-file
#+BEGIN_SRC hledger
fields _, _, date, desc1, desc2, desc3, amount, balance, _
#+END_SRC

It adds a balance assertion to each transaction, using the data helpfully provided by Bogart Bank.

Clearly the cheque account has a pre-existing balance of =R40500=.
To make =hledger= happy, we need to tell it what the opening balance for this account is.

=my-finances/import/bogart/cheque/opening.journal=:
#+NAME: bogart-cheque-opening-balance
#+BEGIN_SRC hledger :tangle my-finances/import/bogart/cheque/opening.journal
2016-02-27 Cheque Account Opening Balance
    Assets:Current:Gawie:Bogart:Cheque              R40500
    Equity:Opening Balances:Gawie:Bogart:Cheque
#+END_SRC


#+NAME: hledger-incomestatement
#+BEGIN_SRC sh :results org :exports both
hledger -f my-finances/import-all.journal incomestatement
#+END_SRC

#+RESULTS: hledger-incomestatement
#+BEGIN_SRC org
Income Statement

Revenues:
          R-37256.28  income:unknown
--------------------
          R-37256.28

Expenses:
           R36500.00  expenses:unknown
--------------------
           R36500.00

Total:
--------------------
            R-756.28


#+END_SRC

* Part 2: Adding More Statements

To Be Continued...
